name: sonar
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=h69a702a_16
  - binutils_impl_linux-64=2.43=h4bf12b8_0
  - ca-certificates=2024.8.30=hbcca054_0
  - gcc=11.4.0=h602e360_13
  - gcc_impl_linux-64=11.4.0=h00c12a0_13
  - kernel-headers_linux-64=3.10.0=h4a8ded7_16
  - ld_impl_linux-64=2.43=h712a8e2_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-devel_linux-64=11.4.0=h8f596e0_113
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libsanitizer=11.4.0=h5763a12_13
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.0=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h4a8ded7_16
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - audiomentations==0.36.1
      - audioread==3.0.1
      - certifi==2024.6.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.20.0
      - decorator==5.1.1
      - dill==0.3.8
      - evaluate==0.4.2
      - filelock==3.15.1
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - grpcio==1.66.1
      - huggingface-hub==0.23.4
      - idna==3.7
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - julius==0.2.7
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.0
      - numpy-rms==0.4.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - opuspy==0.0.3
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.3.0
      - platformdirs==4.2.2
      - pooch==1.8.2
      - protobuf==5.28.2
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pydub==0.25.1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.12.0
      - seaborn==0.12.2
      - six==1.16.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - sympy==1.12.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - torchaudio==2.3.1
      - torchcontrib==0.0.2
      - tqdm==4.66.4
      - transformers==4.42.0.dev0
      - triton==2.3.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==3.0.4
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.20.2
